//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.13 at 01:28:58 PM CST 
//


package com.htcinc.jaxbappresult;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Menuitem2Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Menuitem2Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="menuitem2" type="{}Menuitem2Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Menuitem2Type", propOrder = {
    "menuitem2"
})
public class Menuitem2Type {

    @XmlElement(required = true)
    protected Menuitem2Type menuitem2;

    /**
     * Gets the value of the menuitem2 property.
     * 
     * @return
     *     possible object is
     *     {@link Menuitem2Type }
     *     
     */
    public Menuitem2Type getMenuitem2() {
        return menuitem2;
    }

    /**
     * Sets the value of the menuitem2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Menuitem2Type }
     *     
     */
    public void setMenuitem2(Menuitem2Type value) {
        this.menuitem2 = value;
    }

}
