//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.13 at 01:28:58 PM CST 
//


package com.htcinc.jaxbappresult;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Menuitem1Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Menuitem1Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="menuitem1" type="{}Menuitem1Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Menuitem1Type", propOrder = {
    "menuitem1"
})
public class Menuitem1Type {

    @XmlElement(required = true)
    protected Menuitem1Type menuitem1;

    /**
     * Gets the value of the menuitem1 property.
     * 
     * @return
     *     possible object is
     *     {@link Menuitem1Type }
     *     
     */
    public Menuitem1Type getMenuitem1() {
        return menuitem1;
    }

    /**
     * Sets the value of the menuitem1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Menuitem1Type }
     *     
     */
    public void setMenuitem1(Menuitem1Type value) {
        this.menuitem1 = value;
    }

}
